webpojistovna/pojisteni_app/urls.py
from django.urls import path
from . import views
from . import url_handlers

urlpatterns = [
    path("pojisteni/", views.PojisteniIndex.as_view(), name="pojisteni_index"),
    path("pojistenci/", views.PojistenyIndex.as_view(), name="pojistenci_index"),
    path("<int:pk>/pojisteny_detail/", views.PojistenyCurrent.as_view(), name="pojisteny_detail"),
    path("pojistenci_create/", views.PojistenyCreate.as_view(), name="novy_pojisteny"),
    path("pojisteni_create/", views.PojisteniCreate.as_view(), name="nove_pojisteni"),
    path("udalosti_create/", views.UdalostForm.as_view(), name="udalosti_form"),
    path("pp_create/", views.PojisteniPojistenyCreate.as_view(), name="nove_pp"),
    path("", url_handlers.index_handler),
    path("register/", views.UzivatelViewRegister.as_view(), name="registrace"),
    path("login/", views.UzivatelViewLogin.as_view(), name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("udalosti/", views.UdalostIndex.as_view(), name="udalosti"),
    path("<int:pk>/edit/", views.PojistenyEdit.as_view(), name="edit_pojisteny"),
    path("<int:pk>/edit_pojisteni/", views.PojisteniEdit.as_view(), name="edit_pojisteni"),
    path("<int:pk>/edit_pp/", views.PojisteniPojistenyEdit.as_view(), name="edit_pp"),
    path("<int:pk>/edit_udalost/", views.UdalostiEdit.as_view(), name="edit_udalost"),

]

webpojistovna/webpojistovna/urls.py
from django.contrib import admin
from django.urls import path, include
from . import url_handlers

urlpatterns = [
    path('admin/', admin.site.urls),
    path("pojisteni_app/", include("pojisteni_app.urls")),
    path("", url_handlers.index_handler),
]

webpojistovna/pojisteni_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.

class Pojisteni(models.Model):
    typ_pojisteni = models.CharField(max_length=100)

    def __str__(self):
        return self.typ_pojisteni

    class Meta:
        verbose_name = "Pojištění"
        verbose_name_plural = "Pojištění"

class Pojisteny(models.Model):
    jmeno = models.CharField(max_length=100)
    prijmeni = models.CharField(max_length=100)
    ulice = models.CharField(max_length=200)
    mesto = models.CharField(max_length=200)
    psc = models.IntegerField(default=0)
    tel = models.CharField(max_length=15)
    email = models.CharField(max_length=180)
    pojisteni = models.ManyToManyField(Pojisteni, through='PojisteniPojisteny')

    def __str__(self):
        return "{} {}| {} | {}".format(self.jmeno ,self.prijmeni, self.email, self.tel)

    def formatted_tel(self):
        number = self.tel
        formatted_number = ' '.join([number[i:i + 3] for i in range(0, len(number), 3)])
        return f'{formatted_number}'
    class Meta:
        verbose_name = "Pojištěný"
        verbose_name_plural = "Pojištěnci"

class PojisteniPojisteny(models.Model):
    pojisteni = models.ForeignKey(Pojisteni, on_delete=models.CASCADE)
    pojisteny = models.ForeignKey(Pojisteny, on_delete=models.CASCADE)
    cena = models.IntegerField(default=0)
    predmet_pojisteni = models.CharField(max_length=100)
    platnost_od = models.DateTimeField()
    platnost_do = models.DateTimeField()

    class Meta:
        verbose_name = "Pojištěný - Pojištění"
        verbose_name_plural = "Pojištěný - Pojištění"

    def __str__(self):
        return "{} {} | {}".format(self.pojisteny.jmeno, self.pojisteny.prijmeni, self.pojisteni.typ_pojisteni)

class Udalosti(models.Model):
    cislo_pojistne_smlouvy = models.IntegerField(default=0)
    pojisteni = models.ForeignKey(Pojisteni, on_delete=models.SET_NULL, null=True)
    popis_udalosti = models.CharField(max_length=1000)
    datum_udalosti = models.DateTimeField()

    def __str__(self):
        return "{} | {} | {}".format(self.pojisteni, self.cislo_pojistne_smlouvy, self.datum_udalosti)

    class Meta:
        verbose_name = "Událost"
        verbose_name_plural = "Události"
class UzivatelManager(BaseUserManager):
    def create_user(self, email, password):
        print(self.model)
        if email and password:
            user = self.model(email=self.normalize_email(email))
            user.set_password(password)
            user.save()
            return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password)
        user.is_admin = True
        user.save()
        return user

class Uzivatel(AbstractBaseUser):

    email = models.EmailField(max_length=200, unique=True)
    is_admin = models.BooleanField(default=False)

    class Meta:
        verbose_name = "uživatel"
        verbose_name_plural = "uživatelé"

    objects = UzivatelManager()

    USERNAME_FIELD = "email"

    def __str__(self):
        return "email: {}".format(self.email)

    @property
    def is_staff(self):
        return self.is_admin
    def has_perm(self, perm, obj=None):
        return True
    def has_module_perms(self, app_label):
        return True

webpojistovna/pojisteni_app/forms.py
from django import forms
from .models import Pojisteny, Pojisteni, Uzivatel, PojisteniPojisteny, Udalosti
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column
class PojistenyForm(forms.ModelForm):

    class Meta:
        model = Pojisteny
        fields = ["jmeno", "prijmeni", "ulice", "mesto", "psc", "tel", "email"]
        labels = {"jmeno": "Jméno", "prijmeni": "Příjmení", "ulice": "Ulice", "mesto": "Město", "psc": "PSČ", "tel": "Telefon", "email":" e-mail"}

    def __init__(self, *args, **kwargs):
        super(PojistenyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(

        )
class PojisteniForm(forms.ModelForm):

    class Meta:
        model = Pojisteni
        fields = ["typ_pojisteni"]
        labels = {"typ_pojisteni": "Typ pojištění"}

    def __init__(self, *args, **kwargs):
        super(PojisteniForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout()

class PojisteniPojistenyForm(forms.ModelForm):

    class Meta:
        model = PojisteniPojisteny
        fields = ["pojisteni", "pojisteny", "cena", "predmet_pojisteni", "platnost_od", "platnost_do"]
        labels = {
            "pojisteni": "Pojištění",
            "pojisteny": "Pojištěný",
            "cena": "Cena",
            "predmet_pojisteni": "Předmět pojištění",
            "platnost_od": "Platnost od: |rok-mesic-den| ",
            "platnost_do": "Platnost do: |rok-mesic-den|",
        }



class UdalostiForm(forms.ModelForm):

    class Meta:
        model = Udalosti
        fields = ["cislo_pojistne_smlouvy", "pojisteni", "popis_udalosti", "datum_udalosti"]
        labels = {
            "cislo_pojistne_smlouvy": "Číslo pojistné smlouvy",
            "pojisteni": "Pojištění",
            "popis_udalosti": "Popis události",
            "datum_udalosti": "Datum události",
        }
    def __init__(self, *args, **kwargs):
        super(UdalostiForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
        )


class PojisteniUserForm(forms.ModelForm):

    class Meta:
        model = Pojisteni
        fields = ["typ_pojisteni"]
        labels = {"typ_pojisteni": "Typ pojištění"}

    def __init__(self, *args, **kwargs):
        super(PojisteniUserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout()

class UzivatelForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Uzivatel
        fields = ["email", "password"]

class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ["email", "password"]

webpojistovna/pojisteni_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.views.generic import TemplateView
from django.contrib.auth import login, logout, authenticate
from .models import Pojisteny, Pojisteni, Uzivatel, PojisteniPojisteny, Udalosti
from .forms import PojistenyForm, UzivatelForm, LoginForm, PojisteniForm, PojisteniPojistenyForm, UdalostiForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, Page

# Create your views here.
class PojistenyEdit(LoginRequiredMixin, generic.edit.CreateView):
    form_class = PojistenyForm
    template_name = "pojisteni_app/pojisteny_create.html"

    def get(self, request, pk):
        if not request.user.is_admin:
            messages.info(request, "Nemáte práva pro úpravu pojištěného.")
            return redirect("pojistenci_index")
        try:
            pojisteny = Pojisteny.objects.get(pk=pk)
        except:
            messages.error(request, "Tento pojištěnec neexistuje!")
            return redirect("pojistenci_index")
        form = self.form_class(instance=pojisteny)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk):
        if not request.user.is_admin:
            messages.info(request, "Nemáte práva pro úpravu pojištěnce.")
            return redirect("pojistenci_index")
        form = self.form_class(request.POST)

        if form.is_valid():
            jmeno = form.cleaned_data["jmeno"]
            prijmeni = form.cleaned_data["prijmeni"]
            ulice = form.cleaned_data["ulice"]
            mesto = form.cleaned_data["mesto"]
            psc = form.cleaned_data["psc"]
            tel = form.cleaned_data["tel"]
            email = form.cleaned_data["email"]

            try:
                pojisteny = Pojisteny.objects.get(pk=pk)
            except:
                messages.error(request, "Tento pojištěnec neexistuje!")
                return redirect("pojistenci_index")
            pojisteny.jmeno = jmeno
            pojisteny.prijmeni = prijmeni
            pojisteny.tel = tel
            pojisteny.email = email
            pojisteny.psc = psc
            pojisteny.mesto = mesto
            pojisteny.ulice = ulice
            pojisteny.save()
            return redirect("pojisteny_detail", pk=pojisteny.id)
        return render(request, self.template_name, {"form": form})

class PojisteniEdit(LoginRequiredMixin, generic.edit.CreateView):
    form_class = PojisteniForm
    template_name = "pojisteni_app/pojisteni_create.html"

    def get(self, request, pk):
        if not request.user.is_admin:
            messages.info(request, "Nemáte práva pro úpravu pojištění.")
            return redirect("pojisteni_index")
        try:
            pojisteni = Pojisteni.objects.get(pk=pk)
        except:
            messages.error(request, "Toto pojištění neexistuje!")
            return redirect("pojisteni_index")
        form = self.form_class(instance=pojisteni)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk):
        if not request.user.is_admin:
            messages.info(request, "Nemáte práva pro úpravu pojištění.")
            return redirect("pojisteni_index")
        form = self.form_class(request.POST)

        if form.is_valid():
            typ_pojisteni = form.cleaned_data["typ_pojisteni"]

            try:
                pojisteni = Pojisteni.objects.get(pk=pk)
            except:
                messages.error(request, "Tento pojištěnec neexistuje!")
                return redirect("pojisteni_index")
            pojisteni.typ_pojisteni
            pojisteni.save()
            return redirect("pojisteny_detail", pk=pojisteni.id)
        return render(request, self.template_name, {"form": form})

class UdalostiEdit(LoginRequiredMixin, generic.edit.CreateView):
    form_class = UdalostiForm
    template_name = "pojisteni_app/udalosti_create.html"

    def get(self, request, pk):
        if not request.user.is_admin:
            messages.info(request, "Nemáte práva pro úpravu události.")
            return redirect("udalosti")
        try:
            udalosti = Udalosti.objects.get(pk=pk)
        except:
            messages.error(request, "Tato událost neexistuje!")
            return redirect("udalosti_form")
        form = self.form_class(instance=udalosti)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk):
        if not request.user.is_admin:
            messages.info(request, "Nemáte práva pro úpravu události.")
            return redirect("udalosti_form")
        form = self.form_class(request.POST)

        if form.is_valid():
            cislo_pojistne_smlouvy = form.cleaned_data["cislo_pojistne_smlouvy"]
            pojisteni = form.cleaned_data["pojisteni"]
            popis_udalosti = form.cleaned_data["popis_udalosti"]
            datum_udalosti = form.cleaned_data["datum_udalosti"]

            try:
                udalost = Udalosti.objects.get(pk=pk)
            except:
                messages.error(request, "Tato událost neexistuje!")
                return redirect("udalosti_form")
            udalost.cislo_pojistne_smlouvy
            udalost.pojisteni
            udalost.popis_udalosti
            udalost.datum_udalosti
            pojisteni.save()
            return redirect("udalosti_form")
        return render(request, self.template_name, {"form": form})


class PojisteniPojistenyEdit(LoginRequiredMixin, generic.edit.CreateView):
    form_class = PojisteniPojistenyForm
    template_name = "pojisteni_app/pp_create.html"
    def get(self, request, pk):
        if not request.user.is_admin:
            messages.info(request, "Nemáte práva pro úpravu pojištěného.")
            return redirect("pojisteny_index")
        try:
            pojisteni_pojisteny = PojisteniPojisteny.objects.get(pk=pk)
        except:
            messages.error(request, "Toto pojištění neexistuje!")
            return redirect("pojisteny_index")
        form = self.form_class(instance=pojisteni_pojisteny)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk):
        if not request.user.is_admin:
            messages.info(request, "Nemáte práva pro úpravu pojištěnce.")
            return redirect("pojisteny_index")
        form = self.form_class(request.POST)

        if form.is_valid():
            try:
                pojisteni_pojisteny = PojisteniPojisteny.objects.get(pk=pk)
            except PojisteniPojisteny.DoesNotExist:
                messages.error(request, "Toto pojištění neexistuje!")
                pojisteni_pojisteny = form.instance
                return redirect("pojisteny_detail", pk=pojisteni_pojisteny.pojisteny.pk)
            pojisteni_pojisteny.pojisteni = form.cleaned_data["pojisteni"]
            pojisteni_pojisteny.pojisteny = form.cleaned_data["pojisteny"]
            pojisteni_pojisteny.cena = form.cleaned_data["cena"]
            pojisteni_pojisteny.predmet_pojisteni = form.cleaned_data["predmet_pojisteni"]
            pojisteni_pojisteny.platnost_od = form.cleaned_data["platnost_od"]
            pojisteni_pojisteny.platnost_do = form.cleaned_data["platnost_do"]
            pojisteni_pojisteny.save()

            return redirect("pojisteny_index")
        return render(request, self.template_name, {"form": form})


class PojistenyCurrent(generic.DetailView):
    model = Pojisteny
    template_name = "pojisteni_app/pojisteny_detail.html"



    def get_queryset(self):
        return Pojisteny.objects.all().order_by("-id")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pojisteni_pojisteny = PojisteniPojisteny.objects.filter(pojisteny=self.object).first()
        return context

    def get(self, request, pk):
        try:
            pojisteny = self.get_object()
        except:
            return redirect("pojistenci_index")
        return render(request, self.template_name, {"pojisteny": pojisteny})

    def post(self, request, pk):
        if request.user.is_authenticated:
            if "edit" in request.POST:
                return redirect("edit_pojisteny", pk=self.get_object().pk)
            elif "edit_pojisteni" in request.POST:
                pojisteni_pojisteny = get_object_or_404(PojisteniPojisteny, pk=pk)
                return redirect("edit_pp", pk=pojisteni_pojisteny.pk)
            elif "delete_pojisteni" in request.POST:
                if not request.user.is_admin:
                    messages.info(request, "Nemáte práva pro smazání pojištění.")
                    return redirect("pojisteni_index")
                else:
                    pojisteni_pojisteny_id = request.POST.get("delete_pojisteni")
                    pojisteni_pojisteny = get_object_or_404(PojisteniPojisteny, pk=pojisteni_pojisteny_id)
                    pojisteni_pojisteny.delete()
            elif "nove" in request.POST:
                return redirect("nove_pp")
            else:
                if not request.user.is_admin:
                    messages.info(request, "Nemáte práva pro smazání pojištěnéno.")
                    return redirect("pojistenci_index")
                else:
                    self.get_object().delete()
            return redirect("pojistenci_index")

class PojistenyIndex(generic.ListView):

    template_name = "pojisteni_app/pojisteny_index.html"
    context_object_name = "pojisteny"
    paginate_by = 6

    def get_queryset(self):
        queryset = Pojisteny.objects.all().order_by("-id")
        return queryset  

    def get(self, request):
        try:
            pojisteny = self.get_queryset()
            paginator = Paginator(pojisteny, self.paginate_by)
            page_number = self.request.GET.get('page')
            page = paginator.get_page(page_number)
        except:

webpojistovna/pojisteni_app/templates/pojisteni_app/about.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
    <nav>
        <div class="menu">
            <div id="logo">
            <h3>PojištěníApp</h3>
            </div>
            <div class="flex_box">
                <div class="nav_item"><a href="{% url 'pojistenci_index' %}" >Pojištěnci</a></div>
                <div class="nav_item"><a href="{% url 'pojisteni_index' %}">Pojištění</a></div>
                <div class="nav_item"><a href="{% url 'udalosti' %}">Události</a></div>
                <div class="nav_item"><a href="{% url 'about' %}" class="aktivni">O aplikaci...</a></div>
            </div>
            <div class="flex_box_two">
                {% if user.is_admin %}<div class="nav_item_two"> Admin </div>
                {% else %}
                <div class="nav_item_two"> {{ request.user.email }} </div>
                {% endif %}
                {% if user.is_authenticated %}<div class="nav_item_two"><a href="{% url 'logout' %}">Odhlásit</a></div>{% endif %}
                {% if not user.is_authenticated %}<div class="nav_item_three"><a href="{% url 'registrace' %}">Registrace</a></div>{% endif %}
                {% if not user.is_authenticated %}<div class="nav_item_three"><a href="{% url 'login' %}">Login</a></div>{% endif %}
            </div>
        </div>
    </nav>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <strong><span style="color: #ff564f">Error: {{message}}</span></strong>
                {% elif message.tags == "info" %}
                    <strong><span style="color: #fff64f">Info: {{message}}</span></strong>
                {% else %}
                    <strong><span style="color: #73E460">Zpáva: {{message}}</span></strong>
                {% endif %}
            {% endfor %}
        {% endif %}
    <div class="content">
        <h2>O aplikaci PojištěníApp</h2>
        <p>Aplikace pro evidenci pojistných událostí. <strong>Django</strong></p>


<div class="col-md-4"></div>
{% endblock %}

webpojistovna/pojisteni_app/templates/pojisteni_app/login_form.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<nav>
        <div class="menu">
            <div id="logo">
            <h3>PojištěníApp</h3>
            </div>
            <div class="flex_box">
                <div class="nav_item"><a href="{% url 'pojistenci_index' %}">Pojištěnci</a></div>
                <div class="nav_item"><a href="{% url 'pojisteni_index' %}">Pojištění</a></div>
                <div class="nav_item"><a href="{% url 'udalosti' %}">Události</a></div>
                <div class="nav_item"><a href="{% url 'about' %}">O aplikaci...</a></div>
            </div>
            <div class="flex_box_two">
                {% if user.is_admin %}<div class="nav_item_two"> Admin </div>
                {% else %}
                <div class="nav_item_two"> {{ request.user.email }} </div>
                {% endif %}
                {% if user.is_authenticated %}<div class="nav_item_two"><a href="{% url 'logout' %}">Odhlásit</a></div>{% endif %}
                {% if not user.is_authenticated %}<div class="nav_item_three"><a href="{% url 'registrace' %}">Registrace</a></div>{% endif %}
                {% if not user.is_authenticated %}<div class="nav_item_three"><a href="{% url 'login' %}" class="aktivni">Login</a></div>{% endif %}
            </div>
        </div>
    </nav>

        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <strong><span style="color: #ff564f">Error: {{message}}</span></strong>
                {% elif message.tags == "info" %}
                    <strong><span style="color: #fff64f">Info: {{message}}</span></strong>
                {% else %}
                    <strong><span style="color: #73E460">Zpáva: {{message}}</span></strong>
                {% endif %}
            {% endfor %}
        {% endif %}
    <div class="content">
<h1>Přihlásit se</h1>
<hr>
<div class="col-md-4">
</div>
<div class="col-md-4">
    <section class="login-form">

        <form method="post" action="">
            {% csrf_token %}
            <div class="container-fluid">
                {{form|crispy}}

                <button type="submit" class="btn btn-lg btn-primary btn-block" value="Login">Přihlásit se</button>
            </div>
        </form>
    </section>
</div>

<div class="col-md-4"></div>
{% endblock %}

webpojistovna/pojisteni_app/templates/pojisteni_app/pojisteni_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <nav>
        <div class="menu">
            <div id="logo">
            <h3>PojištěníApp</h3>
            </div>
            <div class="flex_box">
                <div class="nav_item"><a href="{% url 'pojistenci_index' %}">Pojištěnci</a></div>
                <div class="nav_item"><a href="{% url 'pojisteni_index' %}" class="aktivni">Pojištění</a></div>
                <div class="nav_item"><a href="{% url 'udalosti' %}">Události</a></div>
                <div class="nav_item"><a href="{% url 'about' %}">O aplikaci...</a></div>
            </div>
            <div class="flex_box_two">
                {% if user.is_admin %}<div class="nav_item_two"> Admin </div>
                {% else %}
                <div class="nav_item_two"> {{ request.user.email }} </div>
                {% endif %}
                {% if user.is_authenticated %}<div class="nav_item_two"><a href="{% url 'logout' %}">Odhlásit</a></div>{% endif %}
                {% if not user.is_authenticated %}<div class="nav_item_three"><a href="{% url 'registrace' %}">Registrace</a></div>{% endif %}
                {% if not user.is_authenticated %}<div class="nav_item_three"><a href="{% url 'login' %}">Login</a></div>{% endif %}
            </div>
        </div>
    </nav>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <strong><span style="color: #ff564f">Error: {{message}}</span></strong>
                {% elif message.tags == "info" %}
                    <strong><span style="color: #fff64f">Info: {{message}}</span></strong>
                {% else %}
                    <strong><span style="color: #73E460">Zpáva: {{message}}</span></strong>
                {% endif %}
            {% endfor %}
        {% endif %}
    <div class="content">
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit">
</form>
{% endblock %}

webpojistovna/pojisteni_app/templates/pojisteni_app/pojisteny_detail.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load humanize %}
    <nav>
        <div class="menu">
            <div id="logo">
            <h3>PojištěníApp</h3>
            </div>
            <div class="flex_box">
                <div class="nav_item"><a href="{% url 'pojistenci_index' %}" class="aktivni">Pojištěnci</a></div>
                <div class="nav_item"><a href="{% url 'pojisteni_index' %}">Pojištění</a></div>
                <div class="nav_item"><a href="{% url 'udalosti' %}">Události</a></div>
                <div class="nav_item"><a href="{% url 'about' %}">O aplikaci...</a></div>
            </div>
            <div class="flex_box_two">
                {% if user.is_admin %}<div class="nav_item_two"> Admin </div>
                {% else %}
                <div class="nav_item_two"> {{ request.user.email }} </div>
                {% endif %}
                {% if user.is_authenticated %}<div class="nav_item_two"><a href="{% url 'logout' %}">Odhlásit</a></div>{% endif %}
                {% if not user.is_authenticated %}<div class="nav_item_three"><a href="{% url 'registrace' %}">Registrace</a></div>{% endif %}
                {% if not user.is_authenticated %}<div class="nav_item_three"><a href="{% url 'login' %}">Login</a></div>{% endif %}
            </div>
        </div>
    </nav>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <strong><span style="color: #ff564f">Error: {{message}}</span></strong>
                {% elif message.tags == "info" %}
                    <strong><span style="color: #fff64f">Info: {{message}}</span></strong>
                {% else %}
                    <strong><span style="color: #73E460">Zpáva: {{message}}</span></strong>
                {% endif %}
            {% endfor %}
        {% endif %}
    <div class="content">
        <img class="profile_pic" src="{% static 'images/profile.png' %}" alt="profil">
        <h2> {{ pojisteny.jmeno }} {{ pojisteny.prijmeni }} <span class="glyphicon glyphicon-erase"></span></h2>
        <table class="border border-white">
            <tbody>
                <tr><td class="border border-white">{{ pojisteny.ulice }}</td><td class="border border-white text-white">+++++++++++++++++</td> <td class="border border-white">{{ pojisteny.email }}</td></tr>
                <tr><td class="border border-white">{{ pojisteny.mesto }}</td><td class="border border-white text-white">+++++++++++++++++</td> <td class="border border-white">{{ pojisteny.formatted_tel }}</td></tr>
                <tr><td class="border border-white">{{ pojisteny.psc }}</td></tr>
            </tbody>
        </table>
        <div class="spm">
            <h2>Sjednaná pojištění</h2>
        </div>
        <table class="table table-bordered border-black shadow custom-table">
            <thead>
                <tr>
                    <th>Pojištění</th>
                    <th>Částka</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for pojisteni_pojisteny in pojisteny.pojistenipojisteny_set.all %}
                    <tr>
                        <td>{{ pojisteni_pojisteny.pojisteni.typ_pojisteni }}</a></td>
                        <td>{{ pojisteni_pojisteny.cena|intcomma }} Kč</td>
                        <td>
                        {% if user.is_authenticated %}
                        <form method="POST">
                            {% csrf_token %}
                            <button class="edit-button"><a href="{% url 'edit_pp' pk=pojisteni_pojisteny.pk %}" class="text-white text-decoration-none">Editovat</a></button>
                            <button name="delete_pojisteni" class="remove-button" value="{{ pojisteni_pojisteny.id }}">Odstranit</button>
                        </form>
                        {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-light text-muted">Předchozí</a></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only"></span></span></li>
              {% else %}
                <li class="page-item"><a class="page-link btn btn-light" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-light text-primary">Další</a></li>
            {% endif %}
          </ul>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="d-flex gap-3 justify-content-center">
                {% if user.is_admin %}<button name="nove" class="btn btn-primary btn-lg btn-primary mt-5 text-white">Přidat pojištění</button> <button name="edit" class="btn btn-primary btn-lg btn-warning text-white mt-5">Editovat pojištěnce</button>      <button name="delete" class="btn btn-primary btn-lg btn-danger text-white mt-5">Odstranit pojištěnce</button>{% endif %}
            </div>
        </form>
    </div>

{% endblock %}